In [15]:
fruit=["apple","orange","banana","durian","pineapple","kiwi","ciku","papaya","peach"]
#use for loop to find a given fruit name in the list

In [16]:
for item in fruit:
    print(item)

apple
orange
banana
durian
pineapple
kiwi
ciku
papaya
peach

In [17]:
type(fruit)

list

In [7]:
len(fruit)

9

In [8]:
index = 0
for item in fruit:
    print (item,index)
    index +=1
    # index = index + 1

apple 0
orange 1
banana 2
durian 3
pineapple 4
kiwi 5
ciku 6
papaya 7
peach 8

In [49]:
index = 1
for item in fruit:
    print ("The fruit name is " + item + " at index:", index)
    index = index + 1

The fruit name is apple at index: 1
The fruit name is orange at index: 2
The fruit name is banana at index: 3
The fruit name is durian at index: 4
The fruit name is pineapple at index: 5
The fruit name is kiwi at index: 6
The fruit name is ciku at index: 7
The fruit name is papaya at index: 8
The fruit name is peach at index: 9

In [19]:
index = 1
for item in fruit:
    if "apple" == item:
        print("the item apple is in the list at index ", index)
    #print ("The fruit name is " + item + " at index:", index)
    index = index + 1

the item apple is in the list at index  1

In [56]:
for x in range(5,101):
    print(x)

5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [59]:
count = 0
while (count < 10):
    print (count) 
    count = count + 1

0
1
2
3
4
5
6
7
8
9

In [2]:
count = 0
while (count <= 10):
    print (count) 
    count += 1
    #count = count + 1

0
1
2
3
4
5
6
7
8
9
10

In [21]:
count = 0
while (count < 100):
    if count % 2 == 0:
        print ("this is even number: ", count) 
    count = count + 1

this is even number:  0
this is even number:  2
this is even number:  4
this is even number:  6
this is even number:  8
this is even number:  10
this is even number:  12
this is even number:  14
this is even number:  16
this is even number:  18
this is even number:  20
this is even number:  22
this is even number:  24
this is even number:  26
this is even number:  28
this is even number:  30
this is even number:  32
this is even number:  34
this is even number:  36
this is even number:  38
this is even number:  40
this is even number:  42
this is even number:  44
this is even number:  46
this is even number:  48
this is even number:  50
this is even number:  52
this is even number:  54
this is even number:  56
this is even number:  58
this is even number:  60
this is even number:  62
this is even number:  64
this is even number:  66
this is even number:  68
this is even number:  70
this is even number:  72
this is even number:  74
this is even number:  76
this is even number:  78
this is even number:  80
this is even number:  82
this is even number:  84
this is even number:  86
this is even number:  88
this is even number:  90
this is even number:  92
this is even number:  94
this is even number:  96
this is even number:  98

In [23]:
count = 0
while (count < 100):
    if count % 2 == 0:
        print ("this is even number: ", count)
        break
    count = count + 1

this is even number:  0

In [4]:
count = 1
while count <= 100:
        print (count)
        count += 1
        
for i in range (10):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
0
1
2
3
4
5
6
7
8
9

In [72]:
for i in range(3):
    for j in range(1,3):
        print(i,j)

0 1
0 2
1 1
1 2
2 1
2 2

In [74]:
for i in range(1,11):
    for j in range(1,11):
        print(i,j)

1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
2 10
3 1
3 2
3 3
3 4
3 5
3 6
3 7
3 8
3 9
3 10
4 1
4 2
4 3
4 4
4 5
4 6
4 7
4 8
4 9
4 10
5 1
5 2
5 3
5 4
5 5
5 6
5 7
5 8
5 9
5 10
6 1
6 2
6 3
6 4
6 5
6 6
6 7
6 8
6 9
6 10
7 1
7 2
7 3
7 4
7 5
7 6
7 7
7 8
7 9
7 10
8 1
8 2
8 3
8 4
8 5
8 6
8 7
8 8
8 9
8 10
9 1
9 2
9 3
9 4
9 5
9 6
9 7
9 8
9 9
9 10
10 1
10 2
10 3
10 4
10 5
10 6
10 7
10 8
10 9
10 10

In [79]:
for i in range(1,13):
    for j in range(1,13):
        print(i,"x",j,"=",i * j)
        print("------")

1 x 1 = 1
------
1 x 2 = 2
------
1 x 3 = 3
------
1 x 4 = 4
------
1 x 5 = 5
------
1 x 6 = 6
------
1 x 7 = 7
------
1 x 8 = 8
------
1 x 9 = 9
------
1 x 10 = 10
------
1 x 11 = 11
------
1 x 12 = 12
------
2 x 1 = 2
------
2 x 2 = 4
------
2 x 3 = 6
------
2 x 4 = 8
------
2 x 5 = 10
------
2 x 6 = 12
------
2 x 7 = 14
------
2 x 8 = 16
------
2 x 9 = 18
------
2 x 10 = 20
------
2 x 11 = 22
------
2 x 12 = 24
------
3 x 1 = 3
------
3 x 2 = 6
------
3 x 3 = 9
------
3 x 4 = 12
------
3 x 5 = 15
------
3 x 6 = 18
------
3 x 7 = 21
------
3 x 8 = 24
------
3 x 9 = 27
------
3 x 10 = 30
------
3 x 11 = 33
------
3 x 12 = 36
------
4 x 1 = 4
------
4 x 2 = 8
------
4 x 3 = 12
------
4 x 4 = 16
------
4 x 5 = 20
------
4 x 6 = 24
------
4 x 7 = 28
------
4 x 8 = 32
------
4 x 9 = 36
------
4 x 10 = 40
------
4 x 11 = 44
------
4 x 12 = 48
------
5 x 1 = 5
------
5 x 2 = 10
------
5 x 3 = 15
------
5 x 4 = 20
------
5 x 5 = 25
------
5 x 6 = 30
------
5 x 7 = 35
------
5 x 8 = 40
------
5 x 9 = 45
------
5 x 10 = 50
------
5 x 11 = 55
------
5 x 12 = 60
------
6 x 1 = 6
------
6 x 2 = 12
------
6 x 3 = 18
------
6 x 4 = 24
------
6 x 5 = 30
------
6 x 6 = 36
------
6 x 7 = 42
------
6 x 8 = 48
------
6 x 9 = 54
------
6 x 10 = 60
------
6 x 11 = 66
------
6 x 12 = 72
------
7 x 1 = 7
------
7 x 2 = 14
------
7 x 3 = 21
------
7 x 4 = 28
------
7 x 5 = 35
------
7 x 6 = 42
------
7 x 7 = 49
------
7 x 8 = 56
------
7 x 9 = 63
------
7 x 10 = 70
------
7 x 11 = 77
------
7 x 12 = 84
------
8 x 1 = 8
------
8 x 2 = 16
------
8 x 3 = 24
------
8 x 4 = 32
------
8 x 5 = 40
------
8 x 6 = 48
------
8 x 7 = 56
------
8 x 8 = 64
------
8 x 9 = 72
------
8 x 10 = 80
------
8 x 11 = 88
------
8 x 12 = 96
------
9 x 1 = 9
------
9 x 2 = 18
------
9 x 3 = 27
------
9 x 4 = 36
------
9 x 5 = 45
------
9 x 6 = 54
------
9 x 7 = 63
------
9 x 8 = 72
------
9 x 9 = 81
------
9 x 10 = 90
------
9 x 11 = 99
------
9 x 12 = 108
------
10 x 1 = 10
------
10 x 2 = 20
------
10 x 3 = 30
------
10 x 4 = 40
------
10 x 5 = 50
------
10 x 6 = 60
------
10 x 7 = 70
------
10 x 8 = 80
------
10 x 9 = 90
------
10 x 10 = 100
------
10 x 11 = 110
------
10 x 12 = 120
------
11 x 1 = 11
------
11 x 2 = 22
------
11 x 3 = 33
------
11 x 4 = 44
------
11 x 5 = 55
------
11 x 6 = 66
------
11 x 7 = 77
------
11 x 8 = 88
------
11 x 9 = 99
------
11 x 10 = 110
------
11 x 11 = 121
------
11 x 12 = 132
------
12 x 1 = 12
------
12 x 2 = 24
------
12 x 3 = 36
------
12 x 4 = 48
------
12 x 5 = 60
------
12 x 6 = 72
------
12 x 7 = 84
------
12 x 8 = 96
------
12 x 9 = 108
------
12 x 10 = 120
------
12 x 11 = 132
------
12 x 12 = 144
------

In [24]:
import math

for i in range(1,13):
    for j in range(1,13):
        print(i,"^",j,"=",math.pow(i,j))
        print("------")

1 ^ 1 = 1.0
------
1 ^ 2 = 1.0
------
1 ^ 3 = 1.0
------
1 ^ 4 = 1.0
------
1 ^ 5 = 1.0
------
1 ^ 6 = 1.0
------
1 ^ 7 = 1.0
------
1 ^ 8 = 1.0
------
1 ^ 9 = 1.0
------
1 ^ 10 = 1.0
------
1 ^ 11 = 1.0
------
1 ^ 12 = 1.0
------
2 ^ 1 = 2.0
------
2 ^ 2 = 4.0
------
2 ^ 3 = 8.0
------
2 ^ 4 = 16.0
------
2 ^ 5 = 32.0
------
2 ^ 6 = 64.0
------
2 ^ 7 = 128.0
------
2 ^ 8 = 256.0
------
2 ^ 9 = 512.0
------
2 ^ 10 = 1024.0
------
2 ^ 11 = 2048.0
------
2 ^ 12 = 4096.0
------
3 ^ 1 = 3.0
------
3 ^ 2 = 9.0
------
3 ^ 3 = 27.0
------
3 ^ 4 = 81.0
------
3 ^ 5 = 243.0
------
3 ^ 6 = 729.0
------
3 ^ 7 = 2187.0
------
3 ^ 8 = 6561.0
------
3 ^ 9 = 19683.0
------
3 ^ 10 = 59049.0
------
3 ^ 11 = 177147.0
------
3 ^ 12 = 531441.0
------
4 ^ 1 = 4.0
------
4 ^ 2 = 16.0
------
4 ^ 3 = 64.0
------
4 ^ 4 = 256.0
------
4 ^ 5 = 1024.0
------
4 ^ 6 = 4096.0
------
4 ^ 7 = 16384.0
------
4 ^ 8 = 65536.0
------
4 ^ 9 = 262144.0
------
4 ^ 10 = 1048576.0
------
4 ^ 11 = 4194304.0
------
4 ^ 12 = 16777216.0
------
5 ^ 1 = 5.0
------
5 ^ 2 = 25.0
------
5 ^ 3 = 125.0
------
5 ^ 4 = 625.0
------
5 ^ 5 = 3125.0
------
5 ^ 6 = 15625.0
------
5 ^ 7 = 78125.0
------
5 ^ 8 = 390625.0
------
5 ^ 9 = 1953125.0
------
5 ^ 10 = 9765625.0
------
5 ^ 11 = 48828125.0
------
5 ^ 12 = 244140625.0
------
6 ^ 1 = 6.0
------
6 ^ 2 = 36.0
------
6 ^ 3 = 216.0
------
6 ^ 4 = 1296.0
------
6 ^ 5 = 7776.0
------
6 ^ 6 = 46656.0
------
6 ^ 7 = 279936.0
------
6 ^ 8 = 1679616.0
------
6 ^ 9 = 10077696.0
------
6 ^ 10 = 60466176.0
------
6 ^ 11 = 362797056.0
------
6 ^ 12 = 2176782336.0
------
7 ^ 1 = 7.0
------
7 ^ 2 = 49.0
------
7 ^ 3 = 343.0
------
7 ^ 4 = 2401.0
------
7 ^ 5 = 16807.0
------
7 ^ 6 = 117649.0
------
7 ^ 7 = 823543.0
------
7 ^ 8 = 5764801.0
------
7 ^ 9 = 40353607.0
------
7 ^ 10 = 282475249.0
------
7 ^ 11 = 1977326743.0
------
7 ^ 12 = 13841287201.0
------
8 ^ 1 = 8.0
------
8 ^ 2 = 64.0
------
8 ^ 3 = 512.0
------
8 ^ 4 = 4096.0
------
8 ^ 5 = 32768.0
------
8 ^ 6 = 262144.0
------
8 ^ 7 = 2097152.0
------
8 ^ 8 = 16777216.0
------
8 ^ 9 = 134217728.0
------
8 ^ 10 = 1073741824.0
------
8 ^ 11 = 8589934592.0
------
8 ^ 12 = 68719476736.0
------
9 ^ 1 = 9.0
------
9 ^ 2 = 81.0
------
9 ^ 3 = 729.0
------
9 ^ 4 = 6561.0
------
9 ^ 5 = 59049.0
------
9 ^ 6 = 531441.0
------
9 ^ 7 = 4782969.0
------
9 ^ 8 = 43046721.0
------
9 ^ 9 = 387420489.0
------
9 ^ 10 = 3486784401.0
------
9 ^ 11 = 31381059609.0
------
9 ^ 12 = 282429536481.0
------
10 ^ 1 = 10.0
------
10 ^ 2 = 100.0
------
10 ^ 3 = 1000.0
------
10 ^ 4 = 10000.0
------
10 ^ 5 = 100000.0
------
10 ^ 6 = 1000000.0
------
10 ^ 7 = 10000000.0
------
10 ^ 8 = 100000000.0
------
10 ^ 9 = 1000000000.0
------
10 ^ 10 = 10000000000.0
------
10 ^ 11 = 100000000000.0
------
10 ^ 12 = 1000000000000.0
------
11 ^ 1 = 11.0
------
11 ^ 2 = 121.0
------
11 ^ 3 = 1331.0
------
11 ^ 4 = 14641.0
------
11 ^ 5 = 161051.0
------
11 ^ 6 = 1771561.0
------
11 ^ 7 = 19487171.0
------
11 ^ 8 = 214358881.0
------
11 ^ 9 = 2357947691.0
------
11 ^ 10 = 25937424601.0
------
11 ^ 11 = 285311670611.0
------
11 ^ 12 = 3138428376721.0
------
12 ^ 1 = 12.0
------
12 ^ 2 = 144.0
------
12 ^ 3 = 1728.0
------
12 ^ 4 = 20736.0
------
12 ^ 5 = 248832.0
------
12 ^ 6 = 2985984.0
------
12 ^ 7 = 35831808.0
------
12 ^ 8 = 429981696.0
------
12 ^ 9 = 5159780352.0
------
12 ^ 10 = 61917364224.0
------
12 ^ 11 = 743008370688.0
------
12 ^ 12 = 8916100448256.0
------

In [23]:
for num in range(5):
    if num == 2:
        continue
    print(num)

0
1
3
4